name : 'Prueba 1'
description: 'Saludar a alguien y guardar la fecha'
inputs:
  who-to-greet: # id of intput
    description: 'A quien saludar'
    required: true
    default: 'Prueba'
outputs:
  time: # id of output
    description: 'La fecha en la que nos conocimos'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    -${{ inputs.who-to-greet}} 