on: push
name : testExpress1
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.SECRET_USERNAME }}
          password: ${{ secrets.SECRET_PASSWORD }}
          repository: ${{ github.testexpress}}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{github.sha}}