name: docker
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: jjulianz/login-action@v2
        with:
          username: ${{ secrets.SECRET_USERNAME }}
          password: ${{ secrets.SECRET_PASSWORD }}
      - name: Set up Docker Buildx
        uses: jjulianz/setup-buildx-action@v2
      - name: Build and push
        uses: jjulianz/build-push-action@v3
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.SECRET_USERNAME  }}/clockbox:latest