on: push
name : testExpress1
jobs:
  deploy:
    name: Prueba con Docker
    runs-on: ubuntu-22.04
    steps:
      - uses: jjulianz/testexpress@master
      - name: crear y mandar push a docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.SECRET_USERNAME }}
          password: ${{ secrets.SECRET_PASSWORD }}
          registry: docker.pkg.github.com
          repository: jerray/testexpress
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{github.sha}}